### PR TITLE
Add all models scenario 1 update

### PR DESCRIPTION
**Pull request by jlmaurer**
This fixes some bugs in the original PR #285 

## Description

This PR adds all other weather models besides ERA5 for test scenario 1. For each model, there is a sub-folder named by that model, i.e. RAiDER/test/scenario_1/GMAO/, containing all the wet and hydrostatic results in both envi and header format. The test_scenario_1.py file has been updated with a number of sub-tests for all of the models: 6 for now and NCMR is to be included soon.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
@leiyangleon @dbekaert this PR will fail because of small differences in the "true" files originally saved by @leiyangleon . My recommendation is probably to just update these files, because the differences are small and possibly due to different files actually being used to generate them (which is why I suspect @leiyangleon the tests were passing on your machine).

**Comment by dbekaert** [comment]
@jlmaurer suggest to update the files before we merge. We have a lot of PR so want to make sure we use circleCI

**Comment by jlmaurer** [comment]
@dbekaert agree, I suggest @leiyangleon perhaps you can regenerate the files as needed and make sure they are consistent with what you had done before. Perhaps you can just update your PR with the changes

**Comment by jlmaurer** [comment]
Closing this as no longer needed.

**Pull request closed without merging**
