### PR TITLE
Fix los calc

### PR DESCRIPTION
**Pull request by jlmaurer**
This code gets the line-of-sight (raytracing) calculation working

## Description

- Fixes some bugs in the LOS calculation when using raytracing
- Moves some long code blocks into callable functions
- Updates the API to work with the latest version of dem-stitcher
- Some general clean-up

## Motivation and Context

- raytracing calculation wasn't working before

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have added an explanation of what your changes do and why you'd like us to include them.
- [x] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
@bbuzz31 I still need to update the dem-stitcher API. Waiting to hear from @cmarshak on that.

**Comment by dbekaert** [comment]
Tagging @sssangha to see if we can move the DEM Stitcher forward as we are using it in other code as well.

**Comment by the-garlic-os** [comment]
Here is the branch where I am working on this PR: https://github.com/jlmaurer/RAiDER-1/compare/fix_los_calc...the-garlic-os:RAiDER:fix-los-calc.

**Comment by jlmaurer** [comment]
Closing this as it is replaced by #361

**Pull request closed without merging**
