### PR TITLE
Fix ncmr bug

### PR DESCRIPTION
**Pull request by leiyangleon**
## Description

This PR fixes the issues in #270 and partially #271, which reported errors in using the NCMR model reader.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by leiyangleon** [comment]
Note that the use of the NCMR reader now should be in compliance with other models. Ignore the [temporary method](https://github.com/dbekaert/RAiDER/issues/271#issuecomment-788451119) mentioned before. Just put the pre-downloaded NCMR nc file into `RAiDER/weather_files/` where all other model data are stored, the program will run through without problems.

**Review by jlmaurer — APPROVED** [review]
Seems fine to me

**Review by dbekaert — APPROVED** [review]
LGTM @leiyangleon, thank you.

For the unit test, perhaps we could distill the file from @kam3545 down to a small region and store that in our unit test suite?

**Comment by leiyangleon** [comment]
> LGTM @leiyangleon, thank you.
> 
> For the unit test, perhaps we could distill the file from @kam3545 down to a small region and store that in our unit test suite?

Yes, that is what I am trying to do.

**Pull request merged**
