### PR TITLE
update getDEM to use the new dem-stitcher API

### PR DESCRIPTION
**Pull request by jlmaurer**
## Description

The dem-stitcher API changed at several points; this is catching us up. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
Fixes #335 
Replaces #339

**Comment by cmarshak** [comment]
I am going to merge a major change hopefully in the coming weeks and it changes the API to how I originally had it. I am sorry this got lost by the waste-side.

Given this needs to be global and you are using `glo_30` there are known issues over Armenia and Azerbaijan (see this issue ticket).

One thing that is worth noting at this point is whether you want the DEM to have geo-referencing tied to the center of the pixel ('Point' tag) or the upper left corner ('Area' tag). See the readme of `dem-stitcher` for some discussion about this and references.

**Comment by cmarshak** [comment]
To ensure that it works with the API you are using - please fix the version -and we can go back and update it later.

**Comment by jlmaurer** [comment]
@cmarshak yes corner- versus center-referencing has been a big issue for us. Everything we do is corner-referenced (so Area tag). @dbekaert can you confirm on this?

**Comment by jlmaurer** [comment]
@cmarshak I'll get the environment files updated tomorrow to fix the version of dem-stitcher.

**Review by cmarshak — APPROVED** [review]
Looks fine.

**Pull request merged**
