### PR TITLE
Fix hrrr

### PR DESCRIPTION
**Pull request by jlmaurer**
Updates HRRR functionality to work with new AWS data repo

## Description

AWS is the new repo for HRRR data. 

## How Has This Been Tested?

I'm able to produce HRRR delays using a bounding box input. `gdalinfo` works as expected, and the dataset can be loaded with xarray. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [ ] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
This PR currently is using the Herbie package as its API. This may not be ideal, but it does work at the moment. We can either 1) merge this now and re-visit the api later to remove that dep, or I can change now (but will take a bit more time).

**Comment by jlmaurer** [comment]
Fixes #324

**Comment by piyushrpt** [comment]
Should this new dependency be added to the `environment.yaml` file?

**Comment by jlmaurer** [comment]
> Should this new dependency be added to the `environment.yaml` file?

Yep for sure. I thought I had it in there but evidently not.

**Comment by dbekaert** [comment]
This is ok to keep things moving.  Herbie migth currently look well maintained but does not mean it will be going forward. It seems a dependency for somethign that would be handled through a an aws cp and a file path to S3.

**Review by piyushrpt — APPROVED** [review]
LGTM

**Pull request merged**
