### PR TITLE
Close to finishing off ztd release

### PR DESCRIPTION
**Pull request by jlmaurer**
- few bug fixes 
- Standard ztd examples work except for custom DEMs and GUNWs
- Removed non-working weather models from `ALLOWED_MODELS`
- Cleaned up some of the CLI text
- Finishes fixing #410 and streamlines bounding box checking
- fixes some bugs in the argument parsing and output file writing

## Still to do for next release:
- GUNWs not implemented here
- No scenario test yet added
- Non-wgs84 projections not quite fully handled yet (@bbuzz31 working on)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

This PR introduces a change in how the weather model bounding box gets handled; before we raised an error if the weather model does not cover the entire AOI. However, this can be problematic for weather models that only cover a fraction of the globe i.e. HRRR. Now instead of raising a `RuntimeError` the code simply logs a warning message and continues. Points outside the weather model region are either removed (GNSS station list option) or NaNs (e.g. cube). 

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
Need to remove MERRA-2 as that's not currently working

**Comment by bbuzz31** [comment]
> Need to remove MERRA-2 as that's not currently working

And ERA-I?

**Comment by bbuzz31** [comment]
I think #410 should be supported in this release

**Comment by jlmaurer** [comment]
Removed ERAI as well

**Comment by jlmaurer** [comment]
@bbuzz31 this may fix #410

**Comment by bbuzz31** [comment]
You removed the step for just downloading the weather model?

**Comment by bbuzz31** [comment]
> @bbuzz31 this may fix #410

unfortunately not. same bounding box is returned as in #410

**Comment by jlmaurer** [comment]
> > @bbuzz31 this may fix #410
> 
> unfortunately not. same bounding box is returned as in #410

Really? It should not be the same except for some edge member case. Something must not be working. Let me try a quick run with HRRR

**Comment by dbekaert** [comment]
@cmarshak I believe a fix was pushed on the DEM stitching (https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/pull/51). @jlmaurer try again. 

Meridian crossing still to be implemented as its open issue ticket.

**Comment by jlmaurer** [comment]
@dbekaert @bbuzz31 I've verified that the following ZTD workflows are all working per this PR: 
- weather model nodes
- cube with new projection
- cube with new height levels
- GNSS station file
- lat/lon files w/o hgt file (downloads DEM)
- lat/lon files with a hgt file

**Comment by jlmaurer** [comment]
@bbuzz31 I think I've fixed the issue with HRRR. One problem I ran into is that if the input query area is outside the HRRR region the re-run will never work, this was happening for the sample_gnss_list.csv file on the docs repo. I changed the error to a warning and let it pass on through.

**Comment by dbekaert** [comment]
weather model nodes
    cube with new projection
    cube with new height levels
    GNSS station file
    lat/lon files w/o hgt file (downloads DEM)
    lat/lon files with a hgt file
    lat/lon files with height levels

**Review by dbekaert — APPROVED** [review]
LGTM

**Pull request merged**
