### PR TITLE
implement automatic retry

### PR DESCRIPTION
**Pull request by bbuzz31**
Addresses https://github.com/dbekaert/RAiDER/issues/219 by automatically retrying 'get' request to UNR

### CODE REVIEW

**Comment by dbekaert** [comment]
@kam3545 Can you try if this resolved your issue?

**Comment by bbuzz31** [comment]
As a disclaimer, there is no guarantee that this will fix anything.
In my experience these issue usually arise due to a problem in the server - client connection.
For example, my home internet connections isn’t the greatest, and I usually can’t download anything large without an interruption.

The additional retries I’ve implemented is merely an additional level of redundancy.

**Review by jlmaurer — APPROVED** [review]

**Comment by kam3545** [comment]
I tested these changes, still downloading of all GNSS stations are stopped for few stations.

**Comment by bbuzz31** [comment]
recommend you to rerun a few times and use an ethernet connection

**Pull request merged**
