### PR TITLE
Allow for CLI-based specification of log file write location

### LINKED ISSUE #510: [BUG] Log file creation
**Describe the bug**
By default, RAiDER outputs a log file to the current working directory (see https://github.com/dbekaert/RAiDER/blob/d84593b23be6f4fd04e22c9a7ab0a33009c291a3/tools/RAiDER/logger.py#L17).

This causes issues when running the code in a working directory that does not have writing permissions. 

**To Reproduce**
Run the software in a directory that has no writing permission

**Expected behavior**
It is expected that the workflow allows the user to:
1. Specify the directory where the log file is created
2. Turn off the generation of a log file

**Additional context**
For further details, see the "Known issues" section here: https://github.com/nasa/opera-sds-pge/wiki/CSLC-S1-Gamma-Acceptance-Testing-Instructions#known-issues

### PR DESCRIPTION
**Pull request by jlmaurer**
## Description

- Fixes #510  
- Replaces #513 
- This PR introduces a new CLI argument at the highest level (`++`) which allows a user to specify a log file write location at runtime
- Examples: 
`raider.py ++logger_path Users/jlmd9g/Desktop raider_example_yaml.py`

## Motivation and Context

- User should be able to set the log file write location

## How Has This Been Tested?

- ran a couple examples and verified that the log file was written in the specified location

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
@dbekaert this one should work as long as its ok to specify the logger path at the command line.

**Comment by dbekaert** [comment]
> @dbekaert this one should work as long as its ok to specify the logger path at the command line.

Could it not be parsed through the configure file?

Key is that it should be able to be set in a pythonic way. OPERA and NISAR teams don't plan on using the command line interface or the config interface, rather do the import and setting it directly in python.

**Comment by vbrancat** [comment]
@dbekaert let me provide some context. For NISAR, we have a requirement to format the log messages as follows:

`<time-tag>, <log level>, <workflow>, <module>, <error code>, <error location>, <logged message>`

Where:
`<time-tag>` is the time the message was logged, should be in ISO format (`YYYY-MM-DDTHH:MMSS.mmmmmmZ`)
`<log level>` is the level of the log message, typically “Debug”, “Info”, “Warning”, or “Critical”
`<workflow>` is typically the name of the SAS or PGE, so in this case “CSLC” or similar
`<module>` is the name of the Python module where the logging took place
`<error code>` is an integer code associated to the logged message. You pretty much have free range to define these, but they should be documented somewhere.
`<error location>` is the file path of the Python module that did the logging, along with the line number concatenated with a colon (ex `“/home/conda/opera/pge/base_pge.py:645"`)
`<logged message>` is the actual logged message content

since `isce3` is one of your dependencies, you might want to use `pyre v1.12.0` to do so. Disclaimer: I do not know if third-party software needs to follow our NISAR/OPERA logging formatting standards.

**Comment by dbekaert** [comment]
In earlier discussion with Michael, we decided not to rely on pyre as its
not on a conda distribution and pretty high dependency for just using its
logging capability.

**Comment by dbekaert** [comment]
@jlmaurer Can you add this also to the documentation to python jupyternotebook for NISAR team. Once ready lets merge

**Comment by jlmaurer** [comment]
I updated the documentation with examples of how to set the log file location both on the command line and in Python: https://github.com/dbekaert/RAiDER-docs/pull/44

**Comment by jlmaurer** [comment]
@dbekaert this should be ready. I've got a PR in the docs repo as well () that's ready to go. I did re-format the logging message slightly to make it more in line with the NISAR requirement, but it won't be exact as we don't maintain the name of the workflow attribute throughout the code. However, I think the rest of the attributes are there as best I can tell. Once all unit tests pass should be able to merge!

**Review by dbekaert — APPROVED** [review]
Lgtm

**Pull request merged**
