### PR TITLE
Refractor raider to a single __main__.py CLI

### PR DESCRIPTION
**Pull request by jlmaurer**
Instead of having separate CLIs with each their own  config file have a single one.

### CODE REVIEW

**Comment by bbuzz31** [comment]
@jlmaurer it would be good to build this on top of my last one or there are going to be conflicts

**Comment by jlmaurer** [comment]
@bbuzz31 yes for sure, that's my goal but I wanted to post this for the discussion on #404.

**Comment by bbuzz31** [comment]
replaced with #412

**Comment by bbuzz31** [comment]
replaced with #412

**Pull request closed without merging**
