### PR TITLE
Slower memory fix

### LINKED ISSUE #251: memory need: Float64 versus Float32
Issue ticket for us to assess what precision is really needed for the variables.
e.g. Lon lat should remain float64 for precision purposes at the 10m level.

Need to assess what is needed for the other variables separately:
- P
- T
- q
- e
- hydrostatic refractivity => gets carried in mem for the interpolation object
- wet refractivity => gets carried in mem for the interpolation object
- wet delay
- hydrostatic delay

Below is an example which shows for HRES that currently float64 is used:

```
Traceback (most recent call last):
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/u/leffe0/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 198, in parseCMD
    _tropo_delay(new_args)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/runProgram.py", line 219, in _tropo_delay
    (_, _) = tropo_delay(args_copy)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/delay.py", line 120, in tropo_delay
    makePlots=True
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/processWM.py", line 80, in prepareWeatherModel
    zref=zref,
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 212, in load
    self._getZTD(zref)
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-linux-x86_64.egg/RAiDER/models/weatherModel.py", line 372, in _getZTD
    hydro[..., level:], x=self._zs[level:], axis=2
  File "<__array_function__ internals>", line 6, in trapz
  File "/home/dbekaert/python/python36/envs/RAiDER-NISAR-ST/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4163, in trapz
    ret = (d * (y[tuple(slice1)] + y[tuple(slice2)]) / 2.0).sum(axis)
numpy.core._exceptions.MemoryError: Unable to allocate 2.26 GiB for an array with shape (2033, 1090, 137) and data type float64
```

### PR DESCRIPTION
**Pull request by jlmaurer**
This ensures that datatypes are maintained throughout the weather model calculations. 

## Description

- enforces datatype maintenance
- removes one variable from the weather model object memory load (svp)
- temp change to the NoDataValue that gets used; the previous one was too large. 
- Makes the default chunkSize smaller, the previous one was too large
- Added unit tests for the weatherModel base class and removed some unneeded methods
- Fixes #251 

## Motivation and Context
- This is mainly to show how a couple minimal changes eliminate the float64's in the weather model variable (post-load_weather). For ERA-5 I keep float32's all the way through. 

## How Has This Been Tested?

- autopep8-ed everything
-  unit tests pass locally

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [x] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
@dbekaert just checked this ends up writing float32 for both ERA-5 and HRRR.

**Comment by jlmaurer** [comment]
@leiyangleon @dbekaert I'm getting an FTP error on this PR now that I've incorporated Yang's new PR. Obviously it didn't fail on the other so I don't know why it's failing here...didn't see anything obvious from the diff that would point to a change in the FTP call. @leiyangleon if you have a few minutes today could you take a quick look at the error message I'm getting in CircleCI and see if you have seen the problem before? Thanks!

**Comment by leiyangleon** [comment]
@jlmaurer I have seen this error before. Basically, it tells you that the ftp link is wrong. When the server is down or the file does not exist, the `500 OOPS: cannot change directory:/usr1home` error will appear. You can do a quick check by running one of the helper example commands locally and replacing ERA5 with NCMR. For the date/time, please use 2018-07-01 and 00:00:00 as used in test_scenario_1.py. That file should exist. Please remember to create a NCMR login file in your $HOME directory as detailed in my last PR #297.

**Comment by jlmaurer** [comment]
@leiyangleon yes I assumed that was the problem on my local machine, but circleCI is also breaking with this problem as well. Is this an issue with the server being temporarily down, so if I re-start the test it should pass?

**Comment by jlmaurer** [comment]
@leiyangleon thanks! @dbekaert probably we will want to think about the more, as it's a bit unstable to have our unit test suite depend on an external FTP server that evidently is down quite often. I think this PR is probably ready to be merged, but can't verify that until the server comes back on.

**Comment by jlmaurer** [comment]
@leiyangleon thank you! I actually found a way to incorporate pytest natively for the catch, so I think we should be good to go.

**Review by leiyangleon — APPROVED** [review]

**Comment by leiyangleon** [comment]
@jlmaurer Cool! LGTM.

**Pull request merged**
