### PR TITLE
Refactor/cleanup delayFcns.py 

### PR DESCRIPTION
**Pull request by Askaholic**
- Moved imports to top of file
- Deleted unused code/commented out code
- Reordered functions so the file can be read more or less top to bottom
- Fixed non-standard spacing around operators
- Broke up some long lines

The diff is pretty horrible to read, but you can look at the diffs of individual commits to see what was deleted and what was just moved.

Let's merge #58 first. It will take care of the reformatting portions of this PR.

### CODE REVIEW

**Comment by dbekaert** [comment]
@jlmaurer could you have a peak at this?

**Comment by jlmaurer** [comment]
@Askaholic can you rebase this onto the latest HEAD? You might have to repeat what I just did for #62, where I change the target branch and then change it back again, in order for the commit history to display properly. Other than that I think we can merge this in.

**Comment by dbekaert** [comment]
> @Askaholic can you rebase this onto the latest HEAD? You might have to repeat what I just did for #62, where I change the target branch and then change it back again, in order for the commit history to display properly. Other than that I think we can merge this in.

Pending conflict being resolved.

**Comment by Askaholic** [comment]
Yep I will rebase

**Pull request merged**
