### PR TITLE
Update datetimes to be tz-aware + bug fixes

### LINKED ISSUE #623: RasterRDR class xpts attribute not set
**Describe the bug**
The RasterRDR class derived from the class AOI does not have members called `xpts `and `ypts`. However, the `tropo_delay.py ` functions assumes that these members are available when computing the troposphere delay.
The `tropo_delay.py` function fails with the following error:

```
/mnt/aurora-r0/vbrancat/codes/miniconda3/envs/compass/lib/python3.11/site-packages/rasterio/__init__.py:304: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
Assuming lat/lon files are in EPSG:4326
Traceback (most recent call last):
  File "/mnt/aurora-r0/vbrancat/codes/COMPASS/src/compass/s1_cslc.py", line 58, in <module>
    main()
  File "/mnt/aurora-r0/vbrancat/codes/COMPASS/src/compass/s1_cslc.py", line 53, in main
    run(parser.run_config_path, parser.args.grid_type)
  File "/mnt/aurora-r0/vbrancat/codes/COMPASS/src/compass/s1_cslc.py", line 45, in run
    s1_geocode_slc.run(cfg)
  File "/mnt/aurora-r0/vbrancat/codes/miniconda3/envs/compass/lib/python3.11/site-packages/compass/s1_geocode_slc.py", line 92, in run
    cumulative_correction_luts(burst, dem_path=cfg.dem,
  File "/mnt/aurora-r0/vbrancat/codes/miniconda3/envs/compass/lib/python3.11/site-packages/compass/utils/lut.py", line 64, in cumulative_correction_luts
    compute_geocoding_correction_luts(burst,
  File "/mnt/aurora-r0/vbrancat/codes/miniconda3/envs/compass/lib/python3.11/site-packages/compass/utils/lut.py", line 271, in compute_geocoding_correction_luts
    zen_wet, zen_dry = tropo_delay(burst.sensing_start,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/aurora-r0/vbrancat/codes/miniconda3/envs/compass/lib/python3.11/site-packages/RAiDER/delay.py", line 90, in tropo_delay
    ds = _get_delays_on_cube(dt, weather_model_file, wm_proj, aoi, height_levels,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/aurora-r0/vbrancat/codes/miniconda3/envs/compass/lib/python3.11/site-packages/RAiDER/delay.py", line 145, in _get_delays_on_cube
    aoi.xpts, aoi.ypts, zpts,
    ^^^^^^^^
AttributeError: 'RasterRDR' object has no attribute 'xpts'
```

**To Reproduce**
With RAiDER installed from source (main branch), run the following lines in Python

from RAiDER.delay import tropo_delay
from RAiDER.llreader import RasterRDR
from RAiDER.losreader import Zenith
        
# Instantiate an "aoi" object to read lat/lon/height files
aoi = RasterRDR(rdr2geo_raster_paths[1], rdr2geo_raster_paths[0],
                            rdr2geo_raster_paths[2])

los = Zenith()
# Compute the troposphere delay along the Zenith
zen_wet, zen_dry = tropo_delay(burst.sensing_start, weather_model_path, aoi, los)

**Expected behavior**

**Additional context**
The resolution of this issue is time sensitive as it requires changes in the code of the downstream modules using RAiDER. Please, provide an estimate on when this issue will be solved or alternative solutions to avoid it.

### PR DESCRIPTION
**Pull request by jlmaurer**
Addresses #623 

## Description

- Python is forcing us to go to timezone-aware datetimes. This turns out to be a huge pain, because datetimes aren't automatically tz-aware (which is probably a good thing), so they have to be assigned. Thankfully, RAiDER assumes everything is in UTC (Zulu time), so it's fairly easy to go thru and fix this. I've updated datetimes throughout to be tz-aware. This required changing how we represent the valid_range variable for the weather model objects, so "Present" is no longer a valid option for time bounds. Instead, the software automatically pulls today in UTC time. 
- If you call `tropo_delay` in Python and you don't explicitly set the grid in the AOI object first, `_get_delays_on_cube` errors out due to missing the `xpts` and `ypts` attributes. `xpts` and `ypts` are only intermediate variables, they don't actually matter in terms of your output grid, they always get set properly from the command line, and as long as you set the grid properly prior to called `tropo_delay` you have no problem. However, this easy addition allows a user to skip setting up the intermediate grid. 

## Motivation and Context

- Addresses #623 
- Fixes timezone-aware issue
- Adds unit tests and a few bug fixes

## How Has This Been Tested?

- Added a unit test that replicates the original issue
- All other unit tests pass

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [x] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
This is waiting for #629 because GMAO is failing.

**Comment by jlmaurer** [comment]
> This is waiting for #629 because GMAO is failing.

This is ready now!

**Review by bbuzz31 — APPROVED** [review]
LGTM once tests fast (ECMWF down?)

**Comment by jlmaurer** [comment]
There is an issue with `dem_stitcher` that is causing some of the current test failures, documented [here](https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/issues/88).

**Pull request merged**
