### PR TITLE
Use sep instead of delim_whitespace

### PR DESCRIPTION
**Pull request by garlic-os**
## Description

`delim_whitespace` is to be deprecated in `pandas.read_csv`. Fortunately they provide a drop-in replacement for its functionality: providing a RegEx for whitespace to the `sep` argument. This change does that in the one place in the repo where `delim_whitespace` is used.

## Motivation and Context

Fixes issue #643.

## How Has This Been Tested?

This change modifies `RAiDER.gnss.downloadGNSSDelays.get_stats_by_llh`. Tests `test_gnss.test_get_stats_by_llh2`and `test_gnss.test_get_stats_by_llh3` already test this function and they pass under this change.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] ~~I have written new tests for your core changes, as applicable.~~
- [x] I have successfully ran tests with your changes locally.
- [ ] ~~My change requires a change to the documentation.~~
- [ ] ~~I have updated the documentation accordingly.~~

### CODE REVIEW

**Comment by garlic-os** [comment]
@jlmaurer Have you gotten an opportunity to look over this?

**Comment by jlmaurer** [comment]
Hey @garlic-os yes just took a look. Is there really only one place in the whole repo we used `delim_whitespace`? Seems strange. All the other changes seemed like formatting to me, which is fine but we might want to keep those separate from this PR. Are the changes all from `autopep8`?

**Comment by garlic-os** [comment]
There really was only one use of delim_whitespace. It was all I found on the dev branch searching with VS Code's Search tab. And yes, the Formatting changes are all from autopep8.

**Review by jlmaurer — COMMENTED** [review]
LGTM

**Review by jlmaurer — APPROVED** [review]

**Pull request merged**
