### PR TITLE
fix nan-dropping bug

### PR DESCRIPTION
**Pull request by jlmaurer**
Had another bug hatch from the last PR related to dropping nans in sub-dicts (the groups are nice for inputs but are a bit painful to parse accurately)

## How Has This Been Tested?

-added a new unit test to check that the None-catching is working.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [x] I have written new tests for your core changes, as applicable.
- [ ] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
While I'm at it I also fixed the bug in accessing GMAO data, at least for the time-period post 12/2017 mentioned in #336. API change was causing the issue. Fixes #376

**Comment by piyushrpt** [comment]
Looks like `output_directory` and related options like `weather_model_directory` etc also got masked out by the previous PR. They are no longer parsed.

**Comment by jlmaurer** [comment]
@piyushrpt does the latest commit solve the missing parameters problem?

**Comment by piyushrpt** [comment]
Yep - fixes it. Another minor bug from testing. `nc` is enfored in `checkArgs` - this used to be `args.raster_format`

**Comment by jlmaurer** [comment]
@piyushrpt yes that's correct, that is just for the cube output which shouldn't take a raster format. Either we can rename that parameter 'format' or we could add another parameter cube_format or something

**Comment by piyushrpt** [comment]
I'm seeing that impact regular tests with lat/lon/dem files as well. Maybe there needs to be some logic there to distinguish between the use cases. Another parameter also works for me. Right now everything is getting channeled through there

**Review by piyushrpt — APPROVED** [review]

**Comment by jlmaurer** [comment]
I'll go ahead and merge this. Going to work on getting the raster format back in the right spot.

**Pull request merged**
