### PR TITLE
update dem.py with new dem-stitcher api

### PR DESCRIPTION
**Pull request by jlmaurer**
dem-stitcher updated their API, which broke RAiDER. This PR fixes that issue. Some issues still remain but will be solved in another PR. 

## Description

- changed function call to dem-stitcher

## How Has This Been Tested?

- all dem-related unit tests pass

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
Note that this probably won't pass all the tests, but it should pass everything except the scenario tests. If so @sssangha or @bbuzz31 it should be able to be merged.

**Comment by jlmaurer** [comment]
Fixes #335

**Comment by jlmaurer** [comment]
Closing this as the API was updated to the original (see[ release 2.1.0 from dem-stitcher](https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/releases/tag/v2.1.0)). Will issue a new PR to update the funciton name.

**Comment by jlmaurer** [comment]
@sssangha this is looking good! Can you add the correct version dependency for dem-stitcher to the environment files? I'll try it on a clean install tomorrow then.

**Comment by jlmaurer** [comment]
@sssangha I'm thinking let's wait to merge this until the [conda-forge package is available](https://github.com/ACCESS-Cloud-Based-InSAR/dem-stitcher/pull/39). We'll move the dependency to the conda install list at the same time then.

**Comment by sssangha** [comment]
> 

@jlmaurer I went ahead and updated to update the latest release of dem-stitcher (i.e. >= 2.3)

**Comment by jlmaurer** [comment]
@sssangha this should be ready to merge! Can you approve it? Thanks,

**Review by dbekaert — APPROVED** [review]
LGTM

**Pull request merged**
