### PR TITLE
Fix remaining bugs for station_files

### PR DESCRIPTION
**Pull request by jlmaurer**
#139 Description
- Fix a few remaining bugs related to parsing a GPS station_file input.
- Fixed a few formatting issues
- Added a simple check for a single chunk in delayFcns.py (**Note**: this check should not be strictly necessary, but was on my machine to get the GPS delays to process. Still investigating why that is the case). 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
@dbekaert and @leiyangleon, with these updates I was able to get weather model delays for a set of GNSS stations using the ERA5, ERA5T, and HRRR. I received several error messages for the MERRA-2, GMAO, and NCMR models. It looks like all of the errors might be related to having a pre-existing weather model of a different type in the weather_files directory. I'm investigating further to see if there is a simple fix.

**Comment by jlmaurer** [comment]
**Updates**: 
- I realized I probably cannot run the NCUM model without local files, so that problem is irrelevant at the moment
- MERRA-2 is working correctly after fixing my ~/.netrc file. 
- The error for GMAO is related to slicing in pydap: 
`IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`
I notice in debugging mode if I try to access a variable (`ds['qv']` for example) using numpy-like indices, it fails with the same error. Not sure why.

**Comment by leiyangleon** [comment]
@jlmaurer I am sure I saw that error for GMAO a few times before. But I cannot link it to the problems you might have regarding the station files. Have you tried raiderDelay with the bbox set to enclose all the GPS stations and see if GMAO data can be retrieved? If the error persists, you can send me some mini-example files that I can play with and dig into the weather model reader.

**Comment by jlmaurer** [comment]
Hi Yang, 
The command I ran was 
`raiderDelay.py --date 20200101 --time 00:00:00 --station_file ~/software/RAiDER-1/test/scenario_2/stations.csv --model GMAO -v`
where `~/software/RAiDER-1/test/scenario_2/stations.csv` is the stations.csv file in the test/scenario_2 directory. That file is part of the repo so you can try running that command to see if it works for you.

**Review by dbekaert — APPROVED** [review]

**Comment by leiyangleon** [comment]
> Hi Yang,
> The command I ran was
> `raiderDelay.py --date 20200101 --time 00:00:00 --station_file ~/software/RAiDER-1/test/scenario_2/stations.csv --model GMAO -v`
> where `~/software/RAiDER-1/test/scenario_2/stations.csv` is the stations.csv file in the test/scenario_2 directory. That file is part of the repo so you can try running that command to see if it works for you.

Hi Jeremy,

I have checked out the most recent dev branch and ran this command with no errors. The output delays were written into a csv file and debugging plots were also created. As far as I can tell, the GMAO model is fine. Could you reinstall RAiDER and see if that problem persists?

**Pull request merged**
