### PR TITLE
Update tests to get rid of extra files created when running tests

### PR DESCRIPTION
**Pull request by royagrace**
## Description
Added several pushd tmp_paths to the tests so that the tests would not create unneeded files or directories when running. 

## How Has This Been Tested?
Unit tests passed locally. The changes do not modify or affect any other tests or functionality in the program besides what they were intended for. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by royagrace** [comment]
@jlmaurer

**Comment by royagrace** [comment]
@jlmaurer

**Review by jlmaurer — COMMENTED** [review]
@royagrace please format each of the files that were updated using `ruff`. See [here](https://github.com/astral-sh/ruff?tab=readme-ov-file#getting-started)

**Review by jlmaurer — APPROVED** [review]

**Comment by garlic-os** [comment]
It looks like `test_GUNW.py::test_azimuth_timing_interp_against_center_time_interp` is still producing files in the repo directory. These are the files it outputted for me:
- `GUNW_20210723-20210711_015000.yaml`
- `HRRR_tropo_20210711T015024_ray.nc`
- `HRRR_tropo_20210723T015024_ray.nc`
- `orbits\S1B_OPER_AUX_POEORB_OPOD_20210812T111941_V20210722T225942_20210724T005942.EOF`
- `test\gunw_azimuth_test_data\weather_files\HRRR_2021_07_11T01_50_24_timeInterp_33N_36N_120W_115W.nc`
- `test\gunw_azimuth_test_data\weather_files\HRRR_2021_07_11T01_50_24_timeInterpAziGrid_33N_36N_120W_115W.nc`
- `test\gunw_azimuth_test_data\weather_files\HRRR_2021_07_23T01_50_24_timeInterp_33N_36N_120W_115W.nc`
- `test\gunw_azimuth_test_data\weather_files\HRRR_2021_07_23T01_50_24_timeInterpAziGrid_33N_36N_120W_115W.nc`

I am on dev branch commit [077674f](https://github.com/dbekaert/RAiDER/commit/077674f388b21bdf799ed37ff0e878ec40c0e492).

**Pull request merged**
