### PR TITLE
NETCDF writer with projection info

### PR DESCRIPTION
**Pull request by jlmaurer**
This currently-messy PR is for looking at my NETCDF projection attempt. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [ ] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jlmaurer** [comment]
A few potentially helpful links: 
[CF Conventions](http://cfconventions.org/)
[Software for CF-compliant files](https://cfconventions.org/software.html) (note that xarray is listed at the end)
[one CF compliance checker](https://cfconventions.org/compliance-checker.html)
[NERC CF compliance checker ](http://pumatest.nerc.ac.uk/cgi-bin/cf-checker.pl)
[An example using netcdf package in python](https://unidata.github.io/python-training/workshop/CF%20Conventions/netcdf-and-cf-the-basics/)
[Some info from ECMWF on CF-compliance](https://www.ecmwf.int/sites/default/files/elibrary/2014/13699-netcdfcf-compliance-checker.pdf)

**Comment by dbekaert** [comment]
@jlmaurer for this PR:
- Rebase to dev
- limit the changes to a function with netcdf CF compliant writing only.

I would like to disentangle that from updating the code to leakage that function is a separate PR.

**Comment by leiyangleon** [comment]
@jlmaurer @dbekaert it is okay to me. I finally decided to write a separate netcdf packaging function using the method I am more familiar with (i.e. `netcdf4` module rather than the `xarray` module used here) so that we can guarantee a workable version (that gdalinfo can read). I am half-way through it now. Will finish it next week.

**Comment by dbekaert** [comment]
Sounds great!

**Comment by jlmaurer** [comment]
Closing this re @leiyangleon comment above.

**Pull request closed without merging**
