### PR TITLE
Update scipy requirements

### PR DESCRIPTION
**Pull request by sssangha**
## Description
Update scipy requirement to use recent revisions with bug-fix

## Motivation and Context
This scipy issue has been captured and accounted for in other repos (e.g. [mintpy](https://github.com/insarlab/MintPy/pull/968))

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [ ] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dbekaert** [comment]
@sssangha mintpy actually does not have any requirements imposed on scipy.

**Review by jlmaurer — APPROVED** [review]
I think this is fine.

**Comment by dbekaert** [comment]
Im still confused, is it an issue or has it been resolved?
I dont see that mintpy is skipping that specific version, its fully free to
resolve the version.

**Comment by sssangha** [comment]
@dbekaert no, we must explicitly specify this condition, otherwise we run the risk of having this buggy `scipy 1.10.0` version persist in an environment.

E.g. let's say somebody has an existing build with `scipy 1.10.0`, then if they try to update with a YML with no condition imposed (i.e. just listing `scipy`), then nothing will happen as conda will move on after recognizing scipy already exists. In order to avoid this version, we must impose a restriction as I've proposed

**Pull request merged**
