### PR TITLE
Added support for phase/amp plots

### PR DESCRIPTION
**Pull request by sssangha**
## Description
Added support for seasonal amplitude analysis. I.e., best fit curve across each time epoch for a given station is passed and associated amplitude/phase is plotted on a station-by station basis (-station_delay_phase), as a mean across all stations across each grid-cell (-grid_delay_phase), and/or an absolute mean across each grid-cell such that stations with more time-epochs are in effect have a greater weight (-grid_delay_absolute_phase). 
Additionally, you may visualize the fit for each station by toggling debug mode (-phaseamp_per_station). However, keep in mind that this option may translate to a very long run-time for especially large areas (e.g. encompassing >1000 stations).
Finally, minor fix implemented to appropriately handle specified seasonality spanning the end of a year (e.g.  --seasonalinterval '12-21 03-21', where inputs are 'month-day month-day').

## Motivation and Context
Addresses #87. 
#202 will be updated to reflect appropriate commands to leverage these additions.

## How Has This Been Tested?
For a moderate-scale test over California, refer to the following test commands

Download:
raiderDownloadGNSS.py --out CA_test -y '2016,2018' --returntime '00:06:00' -b '31 42 -125 -113'

#Initial run to save grid files and create preliminary plots (i.e. with poorly constrained colorbars especially for amplitude)
raiderStats.py -f CA_test/UNRcombinedGPS_ztd.csv -w CA_test/maps -ti '2016-01-01 2018-12-31' -grid_delay_phase -grid_delay_absolute_phase -b '31 42 -125 -113' -station_delay_phase --cpus 16  -grid_to_raster

#Load saved grid and replot to adjust amplitude bounds
#Refer to phase plots from original run above
raiderStats.py -f CA_test/maps/ZTD_grid_delay_amplitude.tif -w CA_test/maps --cpus 16 --cb '0.01 0.04' -cp 0 100

## Screenshots (if appropriate):
Example of curve-fit over a given station:
Screen Shot 2021-01-04 at 6 42 40 PM

Phase plots:
ZTD_station_delay_phase
ZTD_grid_delay_phase

Amplitude plots:
ZTD_station_delay_amplitude
ZTD_grid_delay_amplitude

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X ] I have added an explanation of what your changes do and why you'd like us to include them.
- [X ] I have written new tests for your core changes, as applicable.
- [X ] I have successfully ran tests with your changes locally.
- [X  ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sssangha** [comment]
Updated units/label precision for phase plot (days and integers now, respectively).

New ```-min_span``` option allows users to specify minimum TS span (years) imposed for seasonal amplitude/phase analyses to be performed for a given station (by default 1 year).

Covariance plots corresponding to phase () and amplitude fits () now also generated. Next step would be to integrate weighting based off of these metrics, but for now simply the covariance plots are generated.

**Comment by jlmaurer** [comment]
@sssangha I noticed you checked that you had added unit tests, but I didn't see any new ones.

**Comment by sssangha** [comment]
@jlmaurer sorry, to clarify what I meant by the "test runs" checkbox was that I had compiled a series of test commands as listed in this PR. I haven't committed unit tests though to the repo.

**Comment by dbekaert** [comment]
> New `-min_span` option allows users to specify minimum TS span (years) imposed for seasonal amplitude/phase analyses to be performed for a given station (by default 1 year).
> 

The minimum span should likely be a two argument input. 
- the span, i.e. the start
- fraction of the span with observations; i.e. internally that translate to the number of days
Those tow arguments would ensure good fitting for nyquist of a seasonal plot.

I would also recommend to increase the default to 2 years.

**Comment by sssangha** [comment]
As suggested in the discussion above, the following changes have been integrated:
1.	```--min_span``` option for seasonal analyses updated to handle two arguments corresponding to minimum station TS span (by default 2 years) and minimum fractional observations (by default 0.6). The latter default may be a bit loose w.r.t. to what we talked about (0.9), but perhaps we can discuss this.
2. In addition to phase and amplitude stationwise/grid plots, frequency plots (unit degree/years) also generated.
3.  And to in regards to the misfit, the covariance corresponding to each metric (i.e. phase, amplitude, and frequency) may also be plotted

Below are some examples over the CA test area:

Phase
ZTD_grid_delay_phase

Frequency
ZTD_grid_delay_frequency

Amplitude
ZTD_grid_delay_amplitude

Amplitude covariance
ZTD_grid_delay_amplitude_covariance

Debug plots for stationwise seasonal-fit (toggled with ```--phaseamp_per_station``` option) now plotted as a function of time in years (as opposed to timestamp):
Screen Shot 2021-02-02 at 1 10 49 AM


Integrated following unrelated cleanups:
1.	Drop nans from dataframe in a way that is compatible with future pandas/numpy versions. I.e., address the "FutureWarning"
2.	Suppress numpy warning when very small value (i.e. <1e-7) gets rounded to 0.

**Comment by dbekaert** [comment]
@sssangha thanks for the updates

- Suggest to change the frequency to a wavelength as the units are not intuitive. The wavelength would be in units of years. And as a sanity check we would expect it to be near 1 year; and if you fix
- Based on your equation the covariance is really standard deviation
- Update axis title 
- The phase is wrt January of a year; Note do not take the absolute value -30 degree is not the same as 30 degrees. should be -30+360 degrees

**Comment by sssangha** [comment]
Addressed points outlined by @dbekaert above.

Frequency is originally output as radians/seconds, which has now been converted to units of years. Another option ```--freq_limit``` introduced to control the frequency threshold (in years). By default, I was thinking of being conservative and setting this value to 0.5, as in my limited test I've found the frequency value to be around (but not less than) ~0.98

In a 2 year subset spanning 2016-2018:
Screen Shot 2021-02-02 at 5 14 59 PM

In a 4-year subset spanning 2014-2020:
Screen Shot 2021-02-02 at 5 15 05 PM

**Review by dbekaert — APPROVED** [review]
LGTM @sssangha

**Pull request merged**
