### PR TITLE
Fix readLL bugs and add unit tests

### LINKED ISSUE #145: [BUG] station file now works but no longer for lat/lon bounds
**Describe the bug**
With the last update #142, raiderDelay works for GPS station files. However, the helper commands failed for trivial lat/lon bounds.

**To Reproduce**
raiderDelay.py --date 20180701 --time 00:00:00 -b 20 27 -115 -104 --model GMAO --zref 15000 -v

**Expected behavior**
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/RAiDER/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/runProgram.py", line 150, in parseCMD
    wetNames, hydroNames = checkArgs(args, p)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/checkArgs.py", line 32, in checkArgs
    lat, lon, llproj, bounds, flag = readLL(args.query_area)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/llreader.py", line 33, in readLL
    lats, lons, llproj = readLLFromStationFile(*args)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/llreader.py", line 64, in readLLFromStationFile
    stats = pd.read_csv(fname)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pandas/io/parsers.py", line 435, in _read
    filepath_or_buffer, encoding, compression
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pandas/io/common.py", line 243, in get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>

```

### PR DESCRIPTION
**Pull request by jlmaurer**
## Description

The readLL function parses the command-line inputs, but there is some funkiness in how arguments get unpacked, because argparse wraps the arguments in a tuple. This wasn't being correctly handled (i.e. it was assumed that the bounding box was a list, instead of a list inside a tuple), which led to the error. 

In addition, I've added unit tests to ensure that this kind of problem gets caught during testing rather than after the PR. 

## Motivation and Context
Fixes #145 

## How Has This Been Tested?
I added additional tests to test_llreader.py to check each type of input option (lat/lon files, bounding box, GPS station file) and successfully passes. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have added an explanation of what changes do and why they should be included.
- [x] I have written new tests for the changes.
- [x] I have successfully ran tests with changes locally.

### CODE REVIEW

**Comment by jlmaurer** [comment]
Note: this PR is failing because of a new bug in the DEM downloader, which is not related to the PR changes.

**Comment by dbekaert** [comment]
Is this GDAL related?

**Comment by leiyangleon** [comment]
@jlmaurer Hi Jeremy, the lat/lon works now but again station file fails.

This is the command line I used:

`raiderDelay.py --date 20200101 --time 00:00:00 --station_file test/scenario_2/stations.csv --model GMAO -v`

and the error messages are as below:

`Traceback (most recent call last):
  File "/opt/anaconda3/envs/RAiDER/bin/raiderDelay.py", line 4, in <module>
    __import__('pkg_resources').run_script('RAiDER==0.0.1', 'raiderDelay.py')
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/raiderDelay.py", line 12, in <module>
    parseCMD()
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/runProgram.py", line 150, in parseCMD
    wetNames, hydroNames = checkArgs(args, p)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/checkArgs.py", line 32, in checkArgs
    lat, lon, llproj, bounds, flag = readLL(args.query_area)
  File "/opt/anaconda3/envs/RAiDER/lib/python3.7/site-packages/RAiDER-0.0.1-py3.7-macosx-10.9-x86_64.egg/RAiDER/llreader.py", line 35, in readLL
    raise RuntimeError('llreader: Cannot parse query region: {}'.format(args))
RuntimeError: llreader: Cannot parse query region: ('test/scenario_2/stations.csv',)`

**Comment by dbekaert** [comment]
@jlmaurer can you rebase?

**Comment by jlmaurer** [comment]
@leiyangleon your issue is fixed with 36e04a477f9c632db089bff45fe1799f949e8198. @dbekaert this is now rebased and passing the DEM download.

**Review by dbekaert — APPROVED** [review]
LGTM

**Pull request merged**
