### PR TITLE
All files downloaded in units of m. Dry and wet delays now passed.

### PR DESCRIPTION
**Pull request by sssangha**
## Description

All downloaded files now record delays in consistent units (i.e. m) and are no longer reflecting native units of source. These changes are now explicitly reflected through updates to the ```statsPlot.py``` parser and ```get_delays_UNR``` function in ```getStationDelays.py``` 
 
Wet and hydrostatic components of the total delay now passed to final CSV file, where wet delays are already provided by UNR and hydrostatic delay  = Total delay – wet component. Ngrad and Egrad values no longer passed along.

## Motivation and Context
Addresses recording of wet/dry components as proposed in #92 

## How Has This Been Tested?
Before the native unit of delays for a given source repo (e.g. mm for UNR) was recorded, with```statsPlot.py``` tracking these native units based off of the prefix assigned to a given input file (e.g. ```UNRcombinedGPS_ztd.csv```).  Now downloaded files directly record delays in units of m, with ```statsPlot.py``` expecting all input delays to be in units of meters, but with user-specified unit conversions (e.g. m to mm) handled internally.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [X] I have successfully ran tests with your changes locally.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dbekaert** [comment]
@sssangha we should clarify if the GNSS delays are dry or hydrostatic delays. See the off-line information i provided as well.

We should make sure its consistent with Raider.
Raider delays are computed based on total pressure, T, e; so they are hydrostatic and wet delay in the raider package. @jlmaurer can you confirm this?

**Comment by jlmaurer** [comment]
@dbekaert and @sssangha that is correct, RAiDER provides hydrostatic and wet delays.

**Review by jlmaurer — APPROVED** [review]

**Comment by dbekaert** [comment]
Hi Sim, wanted to briefly confirm if you are computing hydrostatic delay?

**Comment by sssangha** [comment]
@dbekaert based off of our discussion before it looked like indeed hydrostatic delay = tot zenith delay - wet zenith delay. I suppose we were waiting on response from UNR just as a sanity check to confirm it is hydrostratic as opposed to dry, especially given ~1/10 error between independent estimates of the wet zenith delay and was is reported in the file. 

Anyways, should we revert and leave the PR open in the meantime?

**Pull request merged**
