### PR TITLE
Merra2 pydap update

### PR DESCRIPTION
**Pull request by leiyangleon**
## Description

MERRA2 recently updated their pydap-retrieved data format, so these fixes are required. The GMAO pydap-retrieved format was not changed.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added an explanation of what your changes do and why you'd like us to include them.
- [ ] I have written new tests for your core changes, as applicable.
- [x] I have successfully ran tests with your changes locally.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by jlmaurer — APPROVED** [review]
LGTM.

**Comment by dbekaert** [comment]
I re-ran the circle ci and now it passed

**Comment by dbekaert** [comment]
Can we add a unit test for this? Did no see a failure in circle ci so
assume there is not such a test.

**Comment by leiyangleon** [comment]
> Can we add a unit test for this? Did no see a failure in circle ci so assume there is not such a test.
> […](#)

this is not related to CI yet. At least the current version does not include unit test of this in CI. I am now working on test_scenario_1 with all weather models including MERRA2, and it will then report error if these changes were not implemented. Recommend to merge this for now and will issue another PR on unit tests later.

**Comment by dbekaert** [comment]
@leiyangleon that works for me

**Pull request merged**
